databases:
name: tb_wallet
    databaseName: tb_wallet
    user: tb_wallet

 services:
 - type: pserv
   name: pgbouncer
   runtime: docker
   plan: free
   repo: https://github.com/render-oss/docker-pgbouncer
   envVars:
   - key: DATABASE_URL
     fromDatabase:
       name: tb-wallet
       property: connectionString
   - key: POOL_MODE
     value: transaction
   - key: SERVER_RESET_QUERY
     value: DISCARD ALL
   - key: MAX_CLIENT_CONN
     value: 500
   - key: DEFAULT_POOL_SIZE
     value: 50
buildCommand: |
  nvm install 16
  nvm use 16
  yarn install
  yarn build
  yarn migration:run